swagger: '2.0'

info:
  version: "1.0.0"
  title: ID Images API

paths:
  /images/{osuID}:
    get:
      tags:
       - images
      description: "Get an ID card image of a specific person."
      operationId: getImage
      produces:
        - image/jpeg
        - application/json
      parameters:
        - in: path
          name: osuID
          description: "The 9 digit OSU ID number of a person."
          required: true
          type: integer
        - in: query
          name: width
          description: "Resizes image to a pixel value for width while keeping original aspect ratio."
          required: false
          type: integer

      responses:
        "200":
          description: "Successful response"
          schema:
            type: file
          headers:
              Content-type:
                type: string
                description: image/jpeg
        "400":
          description: "Bad request"
          schema:
            $ref: "#/definitions/Error"
        "404":
          description: "Not Found"
          schema:
            $ref: "#/definitions/Error"
        "500":
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/Error"

definitions:
  Error:
    type: object
    properties:
      status:
        type: integer
        format: int32
      developerMessage:
        type: string
      userMesage:
        type: string
      code:
        type: integer
      details:
        type: string